name: Linting my great code

on:
  push:
    branches:
      - main
      - unit_tests

  pull_request:
    branches:
      - main
      - unit_tests
jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

