name: Playwright Tests

on:
  push:
    branches:
      - main
      - demoqa-tests
  pull_request:
    branches:
      - main
      - demoqa-tests
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload reports
      uses: actions/upload-artifact@v3.1.1
      with:
        name: playwright-report
        path: reports
