name: Playwright Tests

on:
  push:
    branches:
      - main
      - demoqa-tests
  pull_request:
    branches:
      - main
      - demoqa-tests
  schedule:
    - cron: '50 1 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install browsers for Playwright
      run: npx playwright install

    - name: Run Playwright tests
      run: |
        if [ "${{ matrix.browser }}" == "chrome" ]; then
          npm run test:chrome
        elif [ "${{ matrix.browser }}" == "firefox" ]; then
          npm run test:firefox
        fi
    
    - name: Run Cucumber tests
      run: npm run test:cucumber

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}
        path: reports
