name: Playwright Tests

on:
  push:
    branches:
      - main
      - demoqa-tests
      - feat-revision
  pull_request:
    branches:
      - main
      - demoqa-tests
  # schedule:
  #   - cron: '50 1 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, cucumber]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install browsers for Playwright
        run: npx playwright install

      - name: Run tests
        run: |
          if [ "${{ matrix.browser }}" = "chromium" ]; then
            npm run test:chrome
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            npm run test:firefox
          elif [ "${{ matrix.browser }}" = "cucumber" ]; then
            xvfb-run -a npm run test:cucumber
          fi

      - name: Upload Playwright reports
        if: matrix.browser != 'cucumber'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: reports

      - name: Upload Cucumber reports
        if: matrix.browser == 'cucumber'
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-report.html
