name: Playwright Tests

on:
  push:
    branches:
      - main
      - demoqa-tests
  pull_request:
    branches:
      - main
      - demoqa-tests
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install browsers for Playwright
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test

    - name: Check page availability
      run: curl -I https://demoqa.com/text-box

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}-${{ github.run_id }}
        path: reports
